/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package dicecalculator;

import java.util.ArrayList;

/**
 *
 * @author Bruno
 */
public class diceCalculatorGUI extends javax.swing.JFrame {

    /**
     * Creates new form diceCalculatorGUI
     */
    public diceCalculatorGUI() {
        initComponents();
        instructionList=new ArrayList<Integer>();
        calculator= (new DiceCalc_Service()).getDiceCalcPort();
        
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        D4 = new javax.swing.JButton();
        D6 = new javax.swing.JButton();
        D8 = new javax.swing.JButton();
        D10 = new javax.swing.JButton();
        D12 = new javax.swing.JButton();
        D20 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtDiceFormula = new javax.swing.JTextArea();
        ButtonAd = new javax.swing.JButton();
        SubButon = new javax.swing.JButton();
        RolButton = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtResult = new javax.swing.JTextArea();
        Clear = new javax.swing.JButton();
        ClearAll = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("DiceCalculator");

        D4.setText("D4");
        D4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                D4ActionPerformed(evt);
            }
        });

        D6.setText("D6");
        D6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                D6ActionPerformed(evt);
            }
        });

        D8.setText("D8");
        D8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                D8ActionPerformed(evt);
            }
        });

        D10.setText("D10");
        D10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                D10ActionPerformed(evt);
            }
        });

        D12.setText("D12");
        D12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                D12ActionPerformed(evt);
            }
        });

        D20.setText("D20");
        D20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                D20ActionPerformed(evt);
            }
        });

        txtDiceFormula.setColumns(20);
        txtDiceFormula.setRows(5);
        jScrollPane1.setViewportView(txtDiceFormula);

        ButtonAd.setText("+");
        ButtonAd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonAdActionPerformed(evt);
            }
        });

        SubButon.setText("-");
        SubButon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SubButonActionPerformed(evt);
            }
        });

        RolButton.setText("Roll");
        RolButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RolButtonActionPerformed(evt);
            }
        });

        txtResult.setColumns(20);
        txtResult.setRows(5);
        jScrollPane3.setViewportView(txtResult);

        Clear.setText("C");
        Clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ClearActionPerformed(evt);
            }
        });

        ClearAll.setText("AC");
        ClearAll.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ClearAllActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(SubButon, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ButtonAd, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(D10)
                            .addComponent(D4, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(D12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(D6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(D20, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(D8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(ClearAll, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(Clear, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(RolButton, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jScrollPane3)))
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(Clear)
                        .addGap(18, 18, 18)
                        .addComponent(ClearAll)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(D4)
                    .addComponent(D6)
                    .addComponent(D8)
                    .addComponent(ButtonAd))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(D10)
                    .addComponent(D12)
                    .addComponent(D20)
                    .addComponent(SubButon))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane3)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(RolButton, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void D4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_D4ActionPerformed
     
        if( instructionList.size()>0 &&(
                instructionList.get(instructionList.size()-1)!=0&&instructionList.get(instructionList.size()-1)!=-1)){
              
              txtDiceFormula.append("+");
              instructionList.add(-1);
        }
        txtDiceFormula.append("D4");
        instructionList.add(4);
    }//GEN-LAST:event_D4ActionPerformed

    private void ButtonAdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonAdActionPerformed
        txtDiceFormula.append("+");
        instructionList.add(-1);
    }//GEN-LAST:event_ButtonAdActionPerformed

    private void SubButonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SubButonActionPerformed
        txtDiceFormula.append("-");
        instructionList.add(0);
    }//GEN-LAST:event_SubButonActionPerformed

    private void RolButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RolButtonActionPerformed
        //calcular!
        String res=calculator.calculateRoll(instructionList);
        txtResult.setText(res);
        // Mandar la Instruccion afuera, Que quede la caga
    }//GEN-LAST:event_RolButtonActionPerformed

    private void D6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_D6ActionPerformed
        
          if( instructionList.size()>0 &&(
                instructionList.get(instructionList.size()-1)!=0&&instructionList.get(instructionList.size()-1)!=-1)){
              
              txtDiceFormula.append("+");
              instructionList.add(-1);
        }
        txtDiceFormula.append("D6");
        instructionList.add(6);
    }//GEN-LAST:event_D6ActionPerformed

    private void D8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_D8ActionPerformed
        if( instructionList.size()>0 &&(
                instructionList.get(instructionList.size()-1)!=0&&instructionList.get(instructionList.size()-1)!=-1)){
              
              txtDiceFormula.append("+");
              instructionList.add(-1);
        }
        txtDiceFormula.append("D8");
        instructionList.add(8);    }//GEN-LAST:event_D8ActionPerformed

    private void D10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_D10ActionPerformed
         if( instructionList.size()>0 &&(
                instructionList.get(instructionList.size()-1)!=0&&instructionList.get(instructionList.size()-1)!=-1)){
              
              txtDiceFormula.append("+");
              instructionList.add(-1);
        }
        txtDiceFormula.append("D10");
        instructionList.add(12); 
    }//GEN-LAST:event_D10ActionPerformed

    private void D12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_D12ActionPerformed
         if( instructionList.size()>0 &&(
                instructionList.get(instructionList.size()-1)!=0&&instructionList.get(instructionList.size()-1)!=-1)){
              
              txtDiceFormula.append("+");
              instructionList.add(-1);
        }
        txtDiceFormula.append("D12");
        instructionList.add(12); 
    }//GEN-LAST:event_D12ActionPerformed

    private void D20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_D20ActionPerformed
         if( instructionList.size()>0){
            if(instructionList.get(instructionList.size()-1)!=0 && instructionList.get(instructionList.size()-1)!=-1 ){
              System.out.println(instructionList.get(instructionList.size()-1));
              txtDiceFormula.append("+");
              instructionList.add(-1);
         }
        }
        txtDiceFormula.append("D20");
        instructionList.add(20); 
    }//GEN-LAST:event_D20ActionPerformed

    private void ClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ClearActionPerformed
        if(instructionList.size()<1){
            System.out.println("MENOR!");
        }else{
            int instruccion=instructionList.get(instructionList.size()-1);
            String txt=txtDiceFormula.getText();
            if(instruccion==-1||instruccion==0){
                txt=txt.substring(0,txt.length()-1);
            }else if(instruccion>9){ //10, 12 o 20
                txt=txt.substring(0,txt.length()-3);
            }else{
                txt=txt.substring(0,txt.length()-2);
            }
            txtDiceFormula.setText(txt);
            instructionList.remove(instructionList.size()-1);
        }
    }//GEN-LAST:event_ClearActionPerformed

    private void ClearAllActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ClearAllActionPerformed
        txtDiceFormula.setText("");
        instructionList.clear();
    }//GEN-LAST:event_ClearAllActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(diceCalculatorGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(diceCalculatorGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(diceCalculatorGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(diceCalculatorGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new diceCalculatorGUI().setVisible(true);
            }
        });
    }

    private ArrayList<Integer> instructionList;
    private DiceCalc calculator;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButtonAd;
    private javax.swing.JButton Clear;
    private javax.swing.JButton ClearAll;
    private javax.swing.JButton D10;
    private javax.swing.JButton D12;
    private javax.swing.JButton D20;
    private javax.swing.JButton D4;
    private javax.swing.JButton D6;
    private javax.swing.JButton D8;
    private javax.swing.JButton RolButton;
    private javax.swing.JButton SubButon;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextArea txtDiceFormula;
    private javax.swing.JTextArea txtResult;
    // End of variables declaration//GEN-END:variables
}
